name: Action on label change

# This workflow has write permissions on the repo
# It must not checkout a PR and run untrusted code

on:
  pull_request_target:
    types:
      - labeled

jobs:
  comment-on-breaking-change-label:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Bug')
    steps:
      - run: |
          echo ${{ toJson(github) }}
